# ParticleX Configuration
# https://github.com/argvchs/hexo-theme-particlex

# Avatar image
avatar: https://static-argvchs.netlify.app/images/avatar.jpg

# Home page info block
headBlockEnable: true

# Home page background image
background: https://static-argvchs.netlify.app/images/home.jpg

# Highlight style
# https://highlightjs.org
highlightStyle: github

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com/search

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        src: /
    About:
        name: id-card
        theme: solid
        src: /about
    Archives:
        name: box-archive
        theme: solid
        src: /archives
    Categories:
        name: bookmark
        theme: solid
        src: /categories
    Tags:
        name: tags
        theme: solid
        src: /tags
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     src: <link-url>

# Side info card
card:
    enable: true
    description: |
        Here's an argvchs...
    iconLinks:
        github:
            name: github
            theme: brands
            link: https://github.com/argvchs
        qq:
            name: qq
            theme: brands
            link: http://wpa.qq.com/msgrd?v=3&uin=3364555156&site=qq&menu=yes
        twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/argvchs
        email:
            name: envelope
            theme: solid
            link: mailto:argvchs@outlook.com
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
    friendLinks:
        Yuzi: https://blog.yuzi.dev
        LynxCatTheThird: https://lynxcatthethird.github.io
        Kaitaku: https://www.kaitaku.xyz
        # <name>: <link-url>

# Footer info
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

# Polyfill
# https://polyfill.io/v3/url-builder
polyfill:
    enable: true
    features:
        - default

# Rendering math with KaTeX
math:
    enable: true

# Article encryption
crypto:
    enable: true

# Search
search:
    enable: true

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy
    sites: # Sites
        {}
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: true
    src: https://giscus.app/client.js
    repo: argvchs/giscus-comments
    repoID: R_kgDOI_uC-w
    category: Announcements
    categoryID: DIC_kwDOI_uC-84CUToF
    mapping: pathname
    strict: 1
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: https://static-argvchs.netlify.app/css/giscus.css
    lang: zh-CN

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {}
        # e.g.:
        # placeholder: Leave a comment
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang: zh-CN
